spring:
  application:
    name: 21_Config_Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ajinkya-Dhavale/Microservices-Config-Server
          clone-on-start: true
server:
  port: 9091