spring:
  cloud:
    gateway:
      routes:
      - id: welcome-api-root
        uri: lb://WELCOME-API
        predicates:
        - Path=/
      - id: welcome-api
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome
      - id: greet-api
        uri: lb://FEIGN-EXAMPLE
        predicates:
        - Path=/greet
  application:
    name: CLOUD-API-GATEWAY
server:
  port: 8085
