spring:
  application:
    name: 29_spring_JWT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/spring
    username: root
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
server:
  port: 8081